# This file was generated by GoReleaser. DO NOT EDIT.
cask "mirador" do
  version "1.1.1"

  on_macos do
    on_arm do
      sha256 "cbdffa0bba0d0469fb1cd6029598db68232c00a048c7d682b424318989f7479c"
      url "https://github.com/miradorlabs/mirador-cli/releases/download/v#{version}/mirador_Darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "ff981e1bfff9eab799adac183adbc8e7092679a136cf314df3ef3fb04db663ea"
      url "https://github.com/miradorlabs/mirador-cli/releases/download/v#{version}/mirador_Darwin_x86_64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "cf08a7418a530081c965f273dc6ca38a3b00a65ea3fa9c99dda4a7a74f97dafb"
      url "https://github.com/miradorlabs/mirador-cli/releases/download/v#{version}/mirador_Linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "d12869ac257e747c9f2f4284b9c6d17865c3694ef4f60cab4f2e763e680a7b1a"
      url "https://github.com/miradorlabs/mirador-cli/releases/download/v#{version}/mirador_Linux_x86_64.tar.gz"
    end
  end

  name "mirador"
  desc "Query Mirador traces, logs, metrics, and dashboards from your terminal"
  homepage "https://mirador.org"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mirador"

  preflight do
    # Downloaded binaries carry macOS's quarantine flag, and Gatekeeper SIGKILLs a
    # quarantined binary the moment anything executes it. That includes the
    # completions generation, which runs during the artifact phase — so this must
    # be a pre-install hook (preflight), not post: strip the flag before the first
    # execution, or the install itself dies (verified against v1.0.1). Linux has
    # no xattr binary, and system_command raises rather than returning non-zero
    # when the executable is missing, so this must be a file check and not a probe.
    if File.executable?("/usr/bin/xattr")
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", "#{staged_path}/mirador"],
                     print_stderr: false
    end
  end

  generate_completions_from_executable "mirador", "completion"

  # No zap stanza required
end
