# This file was generated by GoReleaser. DO NOT EDIT.
cask "mirador" do
  version "1.0.1"

  on_macos do
    on_arm do
      sha256 "d85f572611a78cb50d9659ce96dbc376fe502dd8a893e89ef2c914ba3c09ab4c"
      url "https://github.com/miradorlabs/mirador-cli/releases/download/v#{version}/mirador_Darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "cef7824ae088880fea0fd532bfee2c0c1dac0346c00aa6a2884a8f212d43edf6"
      url "https://github.com/miradorlabs/mirador-cli/releases/download/v#{version}/mirador_Darwin_x86_64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "916a120e012e77c2ebe5579b5f9f759a2f9f61b9f119d59c6555b8b256f880c3"
      url "https://github.com/miradorlabs/mirador-cli/releases/download/v#{version}/mirador_Linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "95ef8a4028350b7fc3c0e3d403a107d7fc4d6fccf11cecdf0ec7b76e02aa9d4f"
      url "https://github.com/miradorlabs/mirador-cli/releases/download/v#{version}/mirador_Linux_x86_64.tar.gz"
    end
  end

  name "mirador"
  desc "Query Mirador traces, logs, metrics, and dashboards from your terminal"
  homepage "https://mirador.org"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mirador"

  preflight do
    # Downloaded binaries carry macOS's quarantine flag, and Gatekeeper SIGKILLs a
    # quarantined binary the moment anything executes it. That includes the completions
    # generation below, which runs during the artifact phase — so this must be a
    # preflight, not a postflight: strip the flag before the first execution, or the
    # install itself dies. Linux has no xattr binary, and system_command raises rather
    # than returning non-zero when the executable is missing, so this must be a file
    # check and not a probe.
    if File.executable?("/usr/bin/xattr")
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", "#{staged_path}/mirador"],
                     print_stderr: false
    end
  end
  generate_completions_from_executable "mirador", "completion"

  # No zap stanza required
end
