# This file was generated by GoReleaser. DO NOT EDIT.
cask "mirador" do
  version "1.0.3"

  on_macos do
    on_arm do
      sha256 "6b9dda5cef51efba65569e79c1969c5e30b98c41ef0090cbcd6245d193a03680"
      url "https://github.com/miradorlabs/mirador-cli/releases/download/v#{version}/mirador_Darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "28160c3f309575d8406ca64c6ecfee003b317c344ac108c215d4735a71a54717"
      url "https://github.com/miradorlabs/mirador-cli/releases/download/v#{version}/mirador_Darwin_x86_64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "678a3c919aec70c95dd05efe368be3eb2e4b2ca44f0a4f53ca7921b69012c9e2"
      url "https://github.com/miradorlabs/mirador-cli/releases/download/v#{version}/mirador_Linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "cfbfc6a2704dd4b445cdc02bb7ef8b92c777c78752eb924aff797c7050b30af3"
      url "https://github.com/miradorlabs/mirador-cli/releases/download/v#{version}/mirador_Linux_x86_64.tar.gz"
    end
  end

  name "mirador"
  desc "Query Mirador traces, logs, metrics, and dashboards from your terminal"
  homepage "https://mirador.org"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mirador"

  preflight do
    # Downloaded binaries carry macOS's quarantine flag, and Gatekeeper SIGKILLs a
    # quarantined binary the moment anything executes it. That includes the
    # completions generation, which runs during the artifact phase — so this must
    # be a pre-install hook (preflight), not post: strip the flag before the first
    # execution, or the install itself dies (verified against v1.0.1). Linux has
    # no xattr binary, and system_command raises rather than returning non-zero
    # when the executable is missing, so this must be a file check and not a probe.
    if File.executable?("/usr/bin/xattr")
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", "#{staged_path}/mirador"],
                     print_stderr: false
    end
  end

  generate_completions_from_executable "mirador", "completion"

  # No zap stanza required
end
