# This file was generated by GoReleaser. DO NOT EDIT.
cask "terma" do
  preflight_steps do
    on_macos do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "terma"], chdir: ".",
                            must_succeed: false, print_stderr: false
    end
  end

  version "0.2.0"

  on_macos do
    on_arm do
      sha256 "caaea96e73b3691f58683d2a06709694f9c37db533876a294e9ec86a5b8b2aed"
      url "https://github.com/miradorlabs/terma-cli/releases/download/v#{version}/terma_Darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "b442546bac879db54b9c52fb07b19ac7459f23f87fe2168c405e929c5c8c522f"
      url "https://github.com/miradorlabs/terma-cli/releases/download/v#{version}/terma_Darwin_x86_64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "cee6f5dd09fadcf9e8b268ba1cad26a4d5f630b39ac4cd167edb99012531f742"
      url "https://github.com/miradorlabs/terma-cli/releases/download/v#{version}/terma_Linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "79688fc11f327c3b05f5d1ae5c8cb741d210e249e08ce3fb5e07ec230bc66306"
      url "https://github.com/miradorlabs/terma-cli/releases/download/v#{version}/terma_Linux_x86_64.tar.gz"
    end
  end

  name "terma"
  desc "Connect coding agents to Terma and stamp the commits they produce"
  homepage "https://terma.ai/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "terma"

  generate_completions_from_executable "terma", "completion"

  # No zap stanza required
end
