# This file was generated by GoReleaser. DO NOT EDIT.
cask "terma" do
  preflight_steps do
    on_macos do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "terma"], chdir: ".",
                            must_succeed: false, print_stderr: false
    end
  end

  version "0.2.4"

  on_macos do
    on_arm do
      sha256 "f1b972d676e66aab3e10d01db3029bd947b42357219f6fbc98e27d25bf5851b5"
      url "https://github.com/miradorlabs/terma-cli/releases/download/v#{version}/terma_Darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "9c0af24e0614b45ba066bf63ab272b77af6e9c0d51fdd4095da5772a91f7d5a2"
      url "https://github.com/miradorlabs/terma-cli/releases/download/v#{version}/terma_Darwin_x86_64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "47a503fa902dccb16ae0b7ed3b5346d82f04fbc294eae089564362ce44c2090f"
      url "https://github.com/miradorlabs/terma-cli/releases/download/v#{version}/terma_Linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "6150387ebe5459395c5e0204f5865fdc99f5f3114f5240708f00dcb8d23ff269"
      url "https://github.com/miradorlabs/terma-cli/releases/download/v#{version}/terma_Linux_x86_64.tar.gz"
    end
  end

  name "terma"
  desc "Connect coding agents to Terma and stamp the commits they produce"
  homepage "https://terma.ai/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "terma"

  generate_completions_from_executable "terma", "completion"

  # No zap stanza required

  caveats <<~EOS
    Next: run `terma setup` in a terminal.
  EOS
end
