# This file was generated by GoReleaser. DO NOT EDIT.
cask "terma" do
  preflight_steps do
    on_macos do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "terma"], chdir: ".",
                            must_succeed: false, print_stderr: false
    end
  end

  version "0.1.1"

  on_macos do
    on_arm do
      sha256 "eb72fce4977e29be19948d04e798c3b05e684c48c6906caf88556ed4470aa97f"
      url "https://github.com/miradorlabs/terma-cli/releases/download/v#{version}/terma_Darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "b12ff7b08b026a53286a05cadff143beb216b4c46d74091fe615239ac2aaaad6"
      url "https://github.com/miradorlabs/terma-cli/releases/download/v#{version}/terma_Darwin_x86_64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "9abd2dc43e49818db55f3216486319e6240647d5b6ac97f31a4a56cdc24ee9e7"
      url "https://github.com/miradorlabs/terma-cli/releases/download/v#{version}/terma_Linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "218cb867a98ee9e9acc86204fb94790f655b54d28591e7349a532854b37c6132"
      url "https://github.com/miradorlabs/terma-cli/releases/download/v#{version}/terma_Linux_x86_64.tar.gz"
    end
  end

  name "terma"
  desc "Connect coding agents to Terma and stamp the commits they produce"
  homepage "https://terma.ai/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "terma"

  generate_completions_from_executable "terma", "completion"

  # No zap stanza required
end
